//
// Created by karel on 24.06.2024.
//

#ifndef STM8S_TOOLCHAIN_WINDEIS_VERSION_BASIC_MODULES_H
#define STM8S_TOOLCHAIN_WINDEIS_VERSION_BASIC_MODULES_H

#endif // STM8S_TOOLCHAIN_WINDEIS_VERSION_BASIC_MODULES_H
